"""
GRC Framework - Report Generator Module
==========================================
Compliance report generation in multiple formats.

Demonstrates:
  - Template-based report generation
  - Multiple output formats (JSON, Markdown, HTML)
  - Data aggregation
  - Executive summary creation
"""

import json
from typing import List, Dict, Any
from datetime import datetime
from pathlib import Path
from dataclasses import asdict

from ..config import get_config
from ..core.utils import format_timestamp, sanitize_filename


class ReportGenerator:
    """
    Generate compliance reports from scan results.
    
    Demonstrates:
      - Builder pattern (configure, then generate)
      - Strategy pattern for different formats
      - Template method pattern
    """
    
    def __init__(self, findings: List[Dict[str, Any]] = None):
        self.findings = findings or []
        self.config = get_config()
        self.generated_at = format_timestamp()
    
    def add_findings(self, findings: List[Dict[str, Any]]) -> "ReportGenerator":
        """Add findings to the report (fluent interface)."""
        self.findings.extend(findings)
        return self
    
    def generate_json(self, output_path: str = None) -> str:
        """Generate JSON report."""
        if not output_path:
            filename = f"report_{sanitize_filename(self.generated_at)}.json"
            output_path = str(Path(self.config.output_dir) / filename)
        
        report = {
            "metadata": {
                "generated_at": self.generated_at,
                "tool": "GRC Framework",
                "version": "1.0.0"
            },
            "summary": self._create_summary(),
            "findings": self.findings
        }
        
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, ensure_ascii=False)
        
        return output_path
    
    def generate_markdown(self, output_path: str = None) -> str:
        """Generate Markdown report."""
        if not output_path:
            filename = f"report_{sanitize_filename(self.generated_at)}.md"
            output_path = str(Path(self.config.output_dir) / filename)
        
        summary = self._create_summary()
        
        md = f"""# Compliance Report

**Generated:** {self.generated_at}  
**Tool:** GRC Framework v1.0.0  
**Profile:** {self.config.aws_profile}

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Findings | {summary['total']} |
| Critical | {summary['by_severity'].get('CRITICAL', 0)} |
| High | {summary['by_severity'].get('HIGH', 0)} |
| Medium | {summary['by_severity'].get('MEDIUM', 0)} |
| Low | {summary['by_severity'].get('LOW', 0)} |
| Compliance Score | {summary['score']}% |

## Findings by Severity

### 🔴 Critical

{self._format_findings_by_severity('CRITICAL')}

### 🟠 High

{self._format_findings_by_severity('HIGH')}

### 🟡 Medium

{self._format_findings_by_severity('MEDIUM')}

### 🟢 Low

{self._format_findings_by_severity('LOW')}

## Remediation Priority

1. Address all CRITICAL findings immediately
2. Remediate HIGH findings within 7 days
3. Address MEDIUM findings within 30 days
4. Plan remediation for LOW findings in next quarter

---
*Report generated by GRC Framework*
"""
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(md)
        
        return output_path
    
    def generate_executive_summary(self) -> str:
        """Generate a brief executive summary."""
        summary = self._create_summary()
        
        status = "✅ COMPLIANT" if summary['score'] >= 90 else \
                 "⚠️  NEEDS ATTENTION" if summary['score'] >= 70 else \
                 "❌ NON-COMPLIANT"
        
        return f"""
GRC Executive Summary
======================
Date: {self.generated_at}
Status: {status}
Score: {summary['score']}%

Findings: {summary['total']} total
  - Critical: {summary['by_severity'].get('CRITICAL', 0)}
  - High: {summary['by_severity'].get('HIGH', 0)}
  - Medium: {summary['by_severity'].get('MEDIUM', 0)}
  - Low: {summary['by_severity'].get('LOW', 0)}

Next Actions:
1. Review critical findings immediately
2. Assign remediation owners
3. Schedule follow-up scan
"""
    
    def _create_summary(self) -> Dict[str, Any]:
        """Create summary statistics."""
        by_severity = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
        
        for finding in self.findings:
            sev = finding.get("severity", "LOW")
            by_severity[sev] = by_severity.get(sev, 0) + 1
        
        # Calculate score (simplified)
        total = len(self.findings)
        if total == 0:
            score = 100
        else:
            weights = {"CRITICAL": 25, "HIGH": 10, "MEDIUM": 3, "LOW": 1}
            penalty = sum(by_severity.get(s, 0) * w for s, w in weights.items())
            score = max(0, 100 - penalty)
        
        return {
            "total": total,
            "by_severity": by_severity,
            "score": score
        }
    
    def _format_findings_by_severity(self, severity: str) -> str:
        """Format findings of a specific severity for Markdown."""
        findings = [f for f in self.findings if f.get("severity") == severity]
        
        if not findings:
            return "*No findings at this severity level.*\n"
        
        lines = []
        for f in findings:
            lines.append(f"- **[{f.get('resource_type')}]** {f.get('resource_id')}")
            lines.append(f"  - *{f.get('finding_type')}* ({f.get('control')})")
            lines.append(f"  - {f.get('description')}")
            lines.append(f"  - **Remediation:** {f.get('remediation')}")
            lines.append("")
        
        return "\n".join(lines)
